# Generated by Django 3.2.14 on 2026-07-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior', '0008_auto_20211004_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbooks',
            name='bookfile',
            field=models.FileField(blank=True, null=True, upload_to='static/bookfiles/'),
        ),
    ]
